mutation login($data: LoginInput) {
  login(data: $data) {
    access_token
    refresh_token
    expires_in
    token_type
  }
}

mutation refresh($data: RefreshTokeninput) {
  refresh_token(data: $data) {
    access_token
    refresh_token
    expires_in
    token_type
  }
}

mutation logout { 
  logout {
    status
    message
  }
}

mutation forgotPassword($data: ForgotPasswordInput!) {
  forgotPassword(data: $data) {
    status
    message
  }
}

mutation updatePassword($data: NewPasswordWithCodeInput!) {
  updateForgottenPassword(data: $data) {
    email
    token
    password
    password_confirmation
  }
}

mutation register($data: RegisterInput!) {
  register(data: $data) {
    name
    email
    fqdn
    password
    password_confirmation
  }
}

mutation checkDomain($fqdn: String!) {
  checkDomain(fqdn: $fqdn) {
    valid
    message
  }
}