mutation login($data: LoginInput) {
  login(data: $data)
}

mutation logout { 
  logout {
    status
    message
  }
}

mutation forgotPassword($data: ForgotPasswordInput!) {
  forgotPassword(data: $data) {
    status
    message
  }
}

mutation updatePassword($data: NewPasswordWithCodeInput!) {
  updateForgottenPassword(data: $data) {
    email
    token
    password
    password_confirmation
  }
}

mutation register($data: RegisterInput!) {
  register(data: $data) {
    status
    message
    redirect
  }
}

mutation checkDomain($fqdn: String!) {
  checkDomain(fqdn: $fqdn) {
    valid
    message
  }
}